export const PRODUCT_TOKEN_SERVICE_NAME = 'PRODUCT_SERVICE';
export const CATEGORY_TOKEN_SERVICE_NAME = 'CATEGORY_SERVICE';
export const USER_TOKEN_SERVICE_NAME = 'USER_SERVICE';
export const ORDER_TOKEN_SERVICE_NAME = 'ORDER_SERVICE';
